name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development
    tags:
      - "*"

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Docker Tag
        id: tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            DOCKER_TAG="${GITHUB_REF:10}"
          elif [[ $GITHUB_REF == refs/heads/development ]]; then
            DOCKER_TAG="dev"
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            DOCKER_TAG="latest"
          else
            DOCKER_TAG="${GITHUB_REF:11}"
          fi
          echo ::set-output name=tag::${DOCKER_TAG}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sonarr_youtubedl:${{ steps.tag.outputs.tag }}
